const TOOLBAR_TYPE = {
    CONTENT_AREA: 1,
    CONTAINER: 2,
    SUB_CONTAINER: 3,
    SUB_CONTAINER_BOTTOM: 4,
    CONTAINER_CONTENT: 5,
    SUB_CONTAINER_CONTENT: 6,
    COMPONENT: 7,
    COMPONENT_BOTTOM: 8,
};

export default TOOLBAR_TYPE;
